// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *Navigation → Links*
 */
export interface NavigationDocumentDataLinksItem {
  /**
   * Label field in *Navigation → Links*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Optional - Label for the link
   * - **API ID Path**: navigation.links[].label
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  label: prismic.TitleField;

  /**
   * Link field in *Navigation → Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link for navigation item
   * - **API ID Path**: navigation.links[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Content for Navigation documents
 */
interface NavigationDocumentData {
  /**
   * Links field in *Navigation*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  links: prismic.GroupField<Simplify<NavigationDocumentDataLinksItem>>;
}

/**
 * Navigation document from Prismic
 *
 * - **API ID**: `navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NavigationDocumentData>,
    "navigation",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | CategorieDetailSlice
  | CategoriesSlice
  | MiniGallerySlice
  | TalkWhatsappSlice
  | IdeasSlice
  | GallerySlice
  | ImageContentSlice
  | ContactSlice
  | FaqsSlice
  | HeroSlice
  | ImageCardsSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Parent field in *Page*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: page.parent
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  parent: prismic.ContentRelationshipField<"page">;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Site Title field in *Settings*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Title of the site
   * - **API ID Path**: settings.siteTitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  siteTitle: prismic.TitleField;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes =
  | NavigationDocument
  | PageDocument
  | SettingsDocument;

/**
 * Item in *CategorieDetail → Default → Primary → images*
 */
export interface CategorieDetailSliceDefaultPrimaryImagesItem {
  /**
   * codeProduct field in *CategorieDetail → Default → Primary → images*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: categorie_detail.default.primary.images[].codeproduct
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  codeproduct: prismic.KeyTextField;

  /**
   * title field in *CategorieDetail → Default → Primary → images*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: categorie_detail.default.primary.images[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * description field in *CategorieDetail → Default → Primary → images*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: categorie_detail.default.primary.images[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * image field in *CategorieDetail → Default → Primary → images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: categorie_detail.default.primary.images[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * image02 field in *CategorieDetail → Default → Primary → images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: categorie_detail.default.primary.images[].image02
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image02: prismic.ImageField<never>;

  /**
   * image03 field in *CategorieDetail → Default → Primary → images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: categorie_detail.default.primary.images[].image03
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image03: prismic.ImageField<never>;

  /**
   * image04 field in *CategorieDetail → Default → Primary → images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: categorie_detail.default.primary.images[].image04
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image04: prismic.ImageField<never>;

  /**
   * image05 field in *CategorieDetail → Default → Primary → images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: categorie_detail.default.primary.images[].image05
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image05: prismic.ImageField<never>;

  /**
   * prices field in *CategorieDetail → Default → Primary → images*
   *
   * - **Field Type**: Table
   * - **Placeholder**: *None*
   * - **API ID Path**: categorie_detail.default.primary.images[].prices
   * - **Documentation**: https://prismic.io/docs/field#table
   */
  prices: prismic.TableField;
}

/**
 * Primary content in *CategorieDetail → Default → Primary*
 */
export interface CategorieDetailSliceDefaultPrimary {
  /**
   * title field in *CategorieDetail → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: categorie_detail.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * description field in *CategorieDetail → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: categorie_detail.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * images field in *CategorieDetail → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: categorie_detail.default.primary.images[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  images: prismic.GroupField<
    Simplify<CategorieDetailSliceDefaultPrimaryImagesItem>
  >;
}

/**
 * Default variation for CategorieDetail Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CategorieDetailSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CategorieDetailSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CategorieDetail*
 */
type CategorieDetailSliceVariation = CategorieDetailSliceDefault;

/**
 * CategorieDetail Shared Slice
 *
 * - **API ID**: `categorie_detail`
 * - **Description**: CategorieDetail
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CategorieDetailSlice = prismic.SharedSlice<
  "categorie_detail",
  CategorieDetailSliceVariation
>;

/**
 * Item in *Categories → Default → Primary → listCategories*
 */
export interface CategoriesSliceDefaultPrimaryListcategoriesItem {
  /**
   * image field in *Categories → Default → Primary → listCategories*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: categories.default.primary.listcategories[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * title field in *Categories → Default → Primary → listCategories*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: categories.default.primary.listcategories[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * description field in *Categories → Default → Primary → listCategories*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: categories.default.primary.listcategories[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * callToActionLink field in *Categories → Default → Primary → listCategories*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: categories.default.primary.listcategories[].calltoactionlink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  calltoactionlink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * callToActionText field in *Categories → Default → Primary → listCategories*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: categories.default.primary.listcategories[].calltoactiontext
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  calltoactiontext: prismic.KeyTextField;
}

/**
 * Item in *Categories → ListShort → Primary → listCategories*
 */
export interface CategoriesSliceListShortPrimaryListcategoriesItem {
  /**
   * image field in *Categories → ListShort → Primary → listCategories*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: categories.listShort.primary.listcategories[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * title field in *Categories → ListShort → Primary → listCategories*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: categories.listShort.primary.listcategories[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * description field in *Categories → ListShort → Primary → listCategories*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: categories.listShort.primary.listcategories[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * callToActionLink field in *Categories → ListShort → Primary → listCategories*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: categories.listShort.primary.listcategories[].calltoactionlink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  calltoactionlink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * callToActionText field in *Categories → ListShort → Primary → listCategories*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: categories.listShort.primary.listcategories[].calltoactiontext
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  calltoactiontext: prismic.KeyTextField;
}

/**
 * Primary content in *Categories → Default → Primary*
 */
export interface CategoriesSliceDefaultPrimary {
  /**
   * title field in *Categories → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: categories.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * description field in *Categories → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: categories.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * listCategories field in *Categories → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: categories.default.primary.listcategories[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  listcategories: prismic.GroupField<
    Simplify<CategoriesSliceDefaultPrimaryListcategoriesItem>
  >;
}

/**
 * Default variation for Categories Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CategoriesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CategoriesSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Categories → ListShort → Primary*
 */
export interface CategoriesSliceListShortPrimary {
  /**
   * title field in *Categories → ListShort → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: categories.listShort.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * description field in *Categories → ListShort → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: categories.listShort.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * listCategories field in *Categories → ListShort → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: categories.listShort.primary.listcategories[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  listcategories: prismic.GroupField<
    Simplify<CategoriesSliceListShortPrimaryListcategoriesItem>
  >;
}

/**
 * ListShort variation for Categories Slice
 *
 * - **API ID**: `listShort`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CategoriesSliceListShort = prismic.SharedSliceVariation<
  "listShort",
  Simplify<CategoriesSliceListShortPrimary>,
  never
>;

/**
 * Slice variation for *Categories*
 */
type CategoriesSliceVariation =
  | CategoriesSliceDefault
  | CategoriesSliceListShort;

/**
 * Categories Shared Slice
 *
 * - **API ID**: `categories`
 * - **Description**: Categories
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CategoriesSlice = prismic.SharedSlice<
  "categories",
  CategoriesSliceVariation
>;

/**
 * Primary content in *Contact → Default → Primary*
 */
export interface ContactSliceDefaultPrimary {
  /**
   * title field in *Contact → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * description field in *Contact → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * name field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * email field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.email
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email: prismic.KeyTextField;

  /**
   * message field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.message
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  message: prismic.KeyTextField;

  /**
   * phone field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.phone
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  phone: prismic.KeyTextField;

  /**
   * calltoactiontext field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.calltoactiontext
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  calltoactiontext: prismic.KeyTextField;

  /**
   * backgroundImage field in *Contact → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.backgroundimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  backgroundimage: prismic.ImageField<never>;
}

/**
 * Default variation for Contact Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Contact*
 */
type ContactSliceVariation = ContactSliceDefault;

/**
 * Contact Shared Slice
 *
 * - **API ID**: `contact`
 * - **Description**: Contact
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactSlice = prismic.SharedSlice<
  "contact",
  ContactSliceVariation
>;

/**
 * Item in *Faqs → Default → Primary → questions*
 */
export interface FaqsSliceDefaultPrimaryQuestionsItem {
  /**
   * title field in *Faqs → Default → Primary → questions*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.default.primary.questions[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * html field in *Faqs → Default → Primary → questions*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.default.primary.questions[].html
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  html: prismic.RichTextField;
}

/**
 * Primary content in *Faqs → Default → Primary*
 */
export interface FaqsSliceDefaultPrimary {
  /**
   * title field in *Faqs → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * description field in *Faqs → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * questions field in *Faqs → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.default.primary.questions[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  questions: prismic.GroupField<Simplify<FaqsSliceDefaultPrimaryQuestionsItem>>;
}

/**
 * Default variation for Faqs Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FaqsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Faqs*
 */
type FaqsSliceVariation = FaqsSliceDefault;

/**
 * Faqs Shared Slice
 *
 * - **API ID**: `faqs`
 * - **Description**: Faqs
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqsSlice = prismic.SharedSlice<"faqs", FaqsSliceVariation>;

/**
 * Item in *Gallery → Default → Primary → images*
 */
export interface GallerySliceDefaultPrimaryImagesItem {
  /**
   * image field in *Gallery → Default → Primary → images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.default.primary.images[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * title field in *Gallery → Default → Primary → images*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.default.primary.images[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * calltoactionlink field in *Gallery → Default → Primary → images*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.default.primary.images[].calltoactionlink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  calltoactionlink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Primary content in *Gallery → Default → Primary*
 */
export interface GallerySliceDefaultPrimary {
  /**
   * images field in *Gallery → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.default.primary.images[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  images: prismic.GroupField<Simplify<GallerySliceDefaultPrimaryImagesItem>>;
}

/**
 * Default variation for Gallery Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GallerySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<GallerySliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Gallery*
 */
type GallerySliceVariation = GallerySliceDefault;

/**
 * Gallery Shared Slice
 *
 * - **API ID**: `gallery`
 * - **Description**: Gallery
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GallerySlice = prismic.SharedSlice<
  "gallery",
  GallerySliceVariation
>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * title field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Titulo
   * - **API ID Path**: hero.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * description field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * backgroundImage field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.backgroundImage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  backgroundImage: prismic.ImageField<never>;

  /**
   * callToActionLink field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.calltoactionlink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  calltoactionlink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * callToActionText field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.calltoactiontext
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  calltoactiontext: prismic.KeyTextField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Hero → TextToRight → Primary*
 */
export interface HeroSliceTextToRightPrimary {
  /**
   * title field in *Hero → TextToRight → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Titulo
   * - **API ID Path**: hero.textToRight.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * description field in *Hero → TextToRight → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.textToRight.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * backgroundImage field in *Hero → TextToRight → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.textToRight.primary.backgroundImage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  backgroundImage: prismic.ImageField<never>;

  /**
   * callToActionLink field in *Hero → TextToRight → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.textToRight.primary.calltoactionlink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  calltoactionlink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * callToActionText field in *Hero → TextToRight → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.textToRight.primary.calltoactiontext
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  calltoactiontext: prismic.KeyTextField;
}

/**
 * TextToRight variation for Hero Slice
 *
 * - **API ID**: `textToRight`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceTextToRight = prismic.SharedSliceVariation<
  "textToRight",
  Simplify<HeroSliceTextToRightPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault | HeroSliceTextToRight;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *Ideas → Default → Primary*
 */
export interface IdeasSliceDefaultPrimary {
  /**
   * title field in *Ideas → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ideas.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * description field in *Ideas → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ideas.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * image field in *Ideas → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: ideas.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * callToActionLink field in *Ideas → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: ideas.default.primary.calltoactionlink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  calltoactionlink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * callToActionText field in *Ideas → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ideas.default.primary.calltoactiontext
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  calltoactiontext: prismic.KeyTextField;
}

/**
 * Default variation for Ideas Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IdeasSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<IdeasSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Ideas*
 */
type IdeasSliceVariation = IdeasSliceDefault;

/**
 * Ideas Shared Slice
 *
 * - **API ID**: `ideas`
 * - **Description**: Ideas
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IdeasSlice = prismic.SharedSlice<"ideas", IdeasSliceVariation>;

/**
 * Item in *ImageCards → Default → Primary → Cards*
 */
export interface ImageCardsSliceDefaultPrimaryCardsItem {
  /**
   * Image field in *ImageCards → Default → Primary → Cards*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_cards.default.primary.cards[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Text field in *ImageCards → Default → Primary → Cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_cards.default.primary.cards[].text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Button Link field in *ImageCards → Default → Primary → Cards*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: image_cards.default.primary.cards[].buttonLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  buttonLink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Button Text field in *ImageCards → Default → Primary → Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_cards.default.primary.cards[].buttonText
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  buttonText: prismic.KeyTextField;
}

/**
 * Primary content in *ImageCards → Default → Primary*
 */
export interface ImageCardsSliceDefaultPrimary {
  /**
   * Heading field in *ImageCards → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_cards.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Cards field in *ImageCards → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: image_cards.default.primary.cards[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  cards: prismic.GroupField<Simplify<ImageCardsSliceDefaultPrimaryCardsItem>>;
}

/**
 * Default variation for ImageCards Slice
 *
 * - **API ID**: `default`
 * - **Description**: ImageCards
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageCardsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageCardsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ImageCards*
 */
type ImageCardsSliceVariation = ImageCardsSliceDefault;

/**
 * ImageCards Shared Slice
 *
 * - **API ID**: `image_cards`
 * - **Description**: ImageCards
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageCardsSlice = prismic.SharedSlice<
  "image_cards",
  ImageCardsSliceVariation
>;

/**
 * Primary content in *ImageContent → Default → Primary*
 */
export interface ImageContentSliceDefaultPrimary {
  /**
   * title field in *ImageContent → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_content.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * subtitle field in *ImageContent → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_content.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.RichTextField;

  /**
   * description field in *ImageContent → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_content.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * image field in *ImageContent → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_content.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for ImageContent Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageContentSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageContentSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ImageContent*
 */
type ImageContentSliceVariation = ImageContentSliceDefault;

/**
 * ImageContent Shared Slice
 *
 * - **API ID**: `image_content`
 * - **Description**: ImageContent
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageContentSlice = prismic.SharedSlice<
  "image_content",
  ImageContentSliceVariation
>;

/**
 * Item in *MiniGallery → Default → Primary → images*
 */
export interface MiniGallerySliceDefaultPrimaryImagesItem {
  /**
   * image field in *MiniGallery → Default → Primary → images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: mini_gallery.default.primary.images[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<"thumbail">;

  /**
   * description field in *MiniGallery → Default → Primary → images*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: mini_gallery.default.primary.images[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * calltoactionlink field in *MiniGallery → Default → Primary → images*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: mini_gallery.default.primary.images[].calltoactionlink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  calltoactionlink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * title field in *MiniGallery → Default → Primary → images*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: mini_gallery.default.primary.images[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;
}

/**
 * Primary content in *MiniGallery → Default → Primary*
 */
export interface MiniGallerySliceDefaultPrimary {
  /**
   * title field in *MiniGallery → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: mini_gallery.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * description field in *MiniGallery → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: mini_gallery.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * images field in *MiniGallery → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: mini_gallery.default.primary.images[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  images: prismic.GroupField<
    Simplify<MiniGallerySliceDefaultPrimaryImagesItem>
  >;
}

/**
 * Default variation for MiniGallery Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MiniGallerySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MiniGallerySliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *MiniGallery*
 */
type MiniGallerySliceVariation = MiniGallerySliceDefault;

/**
 * MiniGallery Shared Slice
 *
 * - **API ID**: `mini_gallery`
 * - **Description**: MiniGallery
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MiniGallerySlice = prismic.SharedSlice<
  "mini_gallery",
  MiniGallerySliceVariation
>;

/**
 * Primary content in *TalkWhatsapp → Default → Primary*
 */
export interface TalkWhatsappSliceDefaultPrimary {
  /**
   * title field in *TalkWhatsapp → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: talk_whatsapp.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * phone field in *TalkWhatsapp → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: talk_whatsapp.default.primary.phone
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  phone: prismic.KeyTextField;

  /**
   * calltoactionlink field in *TalkWhatsapp → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: talk_whatsapp.default.primary.calltoactionlink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  calltoactionlink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for TalkWhatsapp Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TalkWhatsappSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TalkWhatsappSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TalkWhatsapp*
 */
type TalkWhatsappSliceVariation = TalkWhatsappSliceDefault;

/**
 * TalkWhatsapp Shared Slice
 *
 * - **API ID**: `talk_whatsapp`
 * - **Description**: TalkWhatsapp
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TalkWhatsappSlice = prismic.SharedSlice<
  "talk_whatsapp",
  TalkWhatsappSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      NavigationDocument,
      NavigationDocumentData,
      NavigationDocumentDataLinksItem,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      AllDocumentTypes,
      CategorieDetailSlice,
      CategorieDetailSliceDefaultPrimaryImagesItem,
      CategorieDetailSliceDefaultPrimary,
      CategorieDetailSliceVariation,
      CategorieDetailSliceDefault,
      CategoriesSlice,
      CategoriesSliceDefaultPrimaryListcategoriesItem,
      CategoriesSliceDefaultPrimary,
      CategoriesSliceListShortPrimaryListcategoriesItem,
      CategoriesSliceListShortPrimary,
      CategoriesSliceVariation,
      CategoriesSliceDefault,
      CategoriesSliceListShort,
      ContactSlice,
      ContactSliceDefaultPrimary,
      ContactSliceVariation,
      ContactSliceDefault,
      FaqsSlice,
      FaqsSliceDefaultPrimaryQuestionsItem,
      FaqsSliceDefaultPrimary,
      FaqsSliceVariation,
      FaqsSliceDefault,
      GallerySlice,
      GallerySliceDefaultPrimaryImagesItem,
      GallerySliceDefaultPrimary,
      GallerySliceVariation,
      GallerySliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceTextToRightPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      HeroSliceTextToRight,
      IdeasSlice,
      IdeasSliceDefaultPrimary,
      IdeasSliceVariation,
      IdeasSliceDefault,
      ImageCardsSlice,
      ImageCardsSliceDefaultPrimaryCardsItem,
      ImageCardsSliceDefaultPrimary,
      ImageCardsSliceVariation,
      ImageCardsSliceDefault,
      ImageContentSlice,
      ImageContentSliceDefaultPrimary,
      ImageContentSliceVariation,
      ImageContentSliceDefault,
      MiniGallerySlice,
      MiniGallerySliceDefaultPrimaryImagesItem,
      MiniGallerySliceDefaultPrimary,
      MiniGallerySliceVariation,
      MiniGallerySliceDefault,
      TalkWhatsappSlice,
      TalkWhatsappSliceDefaultPrimary,
      TalkWhatsappSliceVariation,
      TalkWhatsappSliceDefault,
    };
  }
}
