// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  categories: dynamic(() => import("./Categories")),
  contact: dynamic(() => import("./Contact")),
  faqs: dynamic(() => import("./Faqs")),
  gallery: dynamic(() => import("./Gallery")),
  hero: dynamic(() => import("./Hero")),
  ideas: dynamic(() => import("./Ideas")),
  image_cards: dynamic(() => import("./ImageCards")),
  image_content: dynamic(() => import("./ImageContent")),
  mini_gallery: dynamic(() => import("./MiniGallery")),
  talk_whatsapp: dynamic(() => import("./TalkWhatsapp")),
};
